
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int noufe = 12;
  public static final int div = 14;
  public static final int id = 13;
  public static final int txtetiqueta = 2;
  public static final int diagonal = 5;
  public static final int cadena = 3;
  public static final int EOF = 0;
  public static final int body = 10;
  public static final int htmlI = 7;
  public static final int error = 1;
  public static final int head = 9;
  public static final int title = 11;
  public static final int htmlF = 8;
  public static final int mayor = 4;
  public static final int igual = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "txtetiqueta",
  "cadena",
  "mayor",
  "diagonal",
  "igual",
  "htmlI",
  "htmlF",
  "head",
  "body",
  "title",
  "noufe",
  "id",
  "div"
  };
}

