
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int rgb = 19;
  public static final int pyc = 8;
  public static final int llaveIzq = 3;
  public static final int coma = 25;
  public static final int numero = 26;
  public static final int llaveDer = 2;
  public static final int border_width = 12;
  public static final int border_color = 11;
  public static final int tf = 20;
  public static final int font_size = 15;
  public static final int font_color = 16;
  public static final int alineacion = 21;
  public static final int punto = 4;
  public static final int EOF = 0;
  public static final int font = 14;
  public static final int height = 17;
  public static final int id = 23;
  public static final int parentesisIzq = 5;
  public static final int width = 18;
  public static final int parentesisDer = 6;
  public static final int border = 10;
  public static final int color = 24;
  public static final int error = 1;
  public static final int align = 13;
  public static final int background = 9;
  public static final int fuente = 22;
  public static final int dospuntos = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveDer",
  "llaveIzq",
  "punto",
  "parentesisIzq",
  "parentesisDer",
  "dospuntos",
  "pyc",
  "background",
  "border",
  "border_color",
  "border_width",
  "align",
  "font",
  "font_size",
  "font_color",
  "height",
  "width",
  "rgb",
  "tf",
  "alineacion",
  "fuente",
  "id",
  "color",
  "coma",
  "numero"
  };
}

