
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int p_import = 43;
  public static final int parentesisIzq = 53;
  public static final int image = 36;
  public static final int imprimir = 15;
  public static final int elements = 24;
  public static final int p_false = 7;
  public static final int coma = 49;
  public static final int igual = 20;
  public static final int corcheteIzq = 51;
  public static final int numeronegativo = 48;
  public static final int from = 42;
  public static final int finReturn = 30;
  public static final int repetir = 17;
  public static final int panel = 41;
  public static final int etiquetaC = 59;
  public static final int si = 19;
  public static final int igualdad = 29;
  public static final int etiquetaA = 58;
  public static final int mientras = 16;
  public static final int p_default = 22;
  public static final int list = 38;
  public static final int menos = 12;
  public static final int menor = 35;
  public static final int inicioReturn = 14;
  public static final int var = 44;
  public static final int llaveIzq = 55;
  public static final int EOF = 0;
  public static final int parentesisDer = 52;
  public static final int pyc = 47;
  public static final int mas = 13;
  public static final int error = 1;
  public static final int text = 40;
  public static final int color = 31;
  public static final int p_char = 2;
  public static final int mayor = 33;
  public static final int pow = 9;
  public static final int item = 23;
  public static final int negacion = 56;
  public static final int or = 26;
  public static final int menorigual = 34;
  public static final int render = 46;
  public static final int spinner = 37;
  public static final int atributo = 21;
  public static final int corcheteDer = 50;
  public static final int xor = 25;
  public static final int id = 6;
  public static final int textfield = 39;
  public static final int multi = 11;
  public static final int mayorigual = 32;
  public static final int numeroentero = 5;
  public static final int diferente = 28;
  public static final int and = 27;
  public static final int llaveDer = 54;
  public static final int component = 45;
  public static final int boton = 57;
  public static final int division = 10;
  public static final int numerodecimal = 4;
  public static final int p_true = 8;
  public static final int diagonal = 60;
  public static final int p_cadena = 3;
  public static final int sino = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "p_char",
  "p_cadena",
  "numerodecimal",
  "numeroentero",
  "id",
  "p_false",
  "p_true",
  "pow",
  "division",
  "multi",
  "menos",
  "mas",
  "inicioReturn",
  "imprimir",
  "mientras",
  "repetir",
  "sino",
  "si",
  "igual",
  "atributo",
  "p_default",
  "item",
  "elements",
  "xor",
  "or",
  "and",
  "diferente",
  "igualdad",
  "finReturn",
  "color",
  "mayorigual",
  "mayor",
  "menorigual",
  "menor",
  "image",
  "spinner",
  "list",
  "textfield",
  "text",
  "panel",
  "from",
  "p_import",
  "var",
  "component",
  "render",
  "pyc",
  "numeronegativo",
  "coma",
  "corcheteDer",
  "corcheteIzq",
  "parentesisDer",
  "parentesisIzq",
  "llaveDer",
  "llaveIzq",
  "negacion",
  "boton",
  "etiquetaA",
  "etiquetaC",
  "diagonal"
  };
}

